### PR TITLE
add alfred-workflow-docs-elastic to Users

### PR DESCRIPTION
**Pull request by spinscale**
Added a link to my workflow for searching the elastic docs. Thx for this package!

### CODE REVIEW

**Comment by sindresorhus** [comment]
Those examples are hard-coded to just those. Can you move it to the `Users` section? See https://github.com/sindresorhus/alfy/pull/13

**Comment by spinscale** [comment]
done

**Comment by sindresorhus** [comment]
Can you also fix the merge conflict?

**Comment by spinscale** [comment]
done

**Pull request merged**
