### PR TITLE
Improve getting started steps

### PR DESCRIPTION
**Pull request by selrond**
After struggling to make my way through creating my first workflow ever, I re-wrote the Alfy's Usage process to be more beginner-friendly.

### CODE REVIEW

**Comment by selrond** [comment]
Is it ok? Or shall I improve it in some way?

**Comment by AntonNiklasson** [comment]
You have two steps with 2.

**Comment by selrond** [comment]
@AntonNiklasson fixed by ce72ce8cc20ec941fc5535bce0ab4fcc83642722

**Comment by selrond** [comment]
@sindresorhus can you merge it to master?

**Comment by alexlafroscia** [comment]
At least personally, I had a great experience with the Yeoman generator. Didn't have to mess with making an Alfred workflow at all, just ran the generator and was off to the races.

I don't like some of the files that it adds by default, or the default style of the code, but it set up Ava and everything I needed to get a workflow running. Maybe it would be better to just direct people to that as the "default" and suggest some changes to the generator, if some things about that could be more clear.

**Comment by selrond** [comment]
@alexlafroscia however useful the tool appears to yourself, you can't just force people to use it. There needs to be a clear manual installation process available.

**Comment by alexlafroscia** [comment]
I mean... I guess? I think "force people to use it" is a bit strong. I'm not sure why someone would want to make things hard when they could make things easy instead 🤷‍♂️

**Comment by selrond** [comment]
@alexlafroscia to put it simply - not everybody finds installing yeoman maybe for just this one case appealing. There definitely needs to be a raw steb-by-step process.

**Comment by alexlafroscia** [comment]
Sure, that's a good point. However, you can one-line it:

```bash
npx -p yo -p generator-alfred -- yo alfred
```

and you're good to go!

**Comment by selrond** [comment]
Hmmm, I've written a step by step process that I wanted to have when first installing Alfy, what's the problem here? We can add both your and mine ways to get it running. Feel free to create a PR to include your solution

**Comment by sindresorhus** [comment]
Thanks :)

**Pull request merged**
