### PR TITLE
Add configurable interval to checking updates and code cleanup

### PR DESCRIPTION
**Pull request by mdeboer**
Checking for updates every time Alfy is run is slowing down the workflow and there is no need to check for updates every time. This PR adds the property `checkUpdates` to control the interval at which is checked for updates. It defaults to check every 1440 minutes (1 day) for updates but you can set it to `true ` to always check for updates.

I included tests and updated the readme 👍

### CODE REVIEW

**Comment by sindresorhus** [comment]
It already only checks once a day: https://github.com/SamVerschueren/alfred-notifier/blob/5aa12bccfd65b5a8d84a03757d77b081c9db4581/check.js#L11 We could make that explicit in the docs though. Not really interested in adding an option for this as once a day is a good default.

**Comment by SamVerschueren** [comment]
It also happens in a separate process so I don't think it is slowing down. https://github.com/SamVerschueren/alfred-notifier/blob/master/index.js

**Comment by mdeboer** [comment]
Well, I commented the line and that made it **a lot** faster! With these changes it all is a lot faster 👍

**Comment by mdeboer** [comment]
I'll see if I can upload a screen recording as the difference is massive but as you guys apparently don't notice any slowing down, I wonder if it's a bug somewhere?

Please, at least have a look at the PR though, all the work including tests have been done.

**Comment by SamVerschueren** [comment]
I was recently thinking about what could been the cause of this. It might be that `readPkgUp` right [here](https://github.com/sindresorhus/alfy/blob/master/lib/update-notification.js#L6) stalls execution, not sure though (@sindresorhus). So maybe it would be better if we refactor those bits. Instead of reading the `package.json` here, we should just spawn a new process with the workflow directory as argument and let the new process check all the rest. That way we aren't doing anything blocking in here.

**Comment by SamVerschueren** [comment]
@mdeboer I might have found the cause of this. Can you test the following for me?

In your local development environment (where you uncommented the `notifier()` call), can you open `node_modules/alfred-notifier`. Now, open [index.js](https://github.com/SamVerschueren/alfred-notifier/blob/master/index.js) and change the content to the following.

```js
module.exports = () => {
	const cp = execa(path.join(__dirname, 'check.js'), {stdio: 'ignore'});
	cp.unref();
};
```

**Comment by mdeboer** [comment]
Will do! 👍

**Comment by mdeboer** [comment]
Unfortunately there still is quite a delay: 91ms. I created a new script and requiring alfy alone is enough to produce this delay.

```javascript
'use strict';

// Require alfy
console.time('alfy');
const alfy = require('alfy');
console.timeEnd('alfy');

// Output 1 item
console.time('output');
alfy.output([{ title: 'test', valid: true }]);
console.timeEnd('output');
```

**Comment by SamVerschueren** [comment]
Alright, will check it in more detail.

**Comment by mdeboer** [comment]
As I mentioned before, my PR fixes the problem for me, though I understand you might want to know what causes the delay.

**Comment by SamVerschueren** [comment]
Yes I know your PR fixes the problem. The thing is that I just want to offload the logic into `alfy-notifier` and let that module handle the checks. Alfy itself doesn't need to know where the timestamp is being stored, it just wants to receive update notification, all the other logic belongs to the notifier module.

**Comment by SamVerschueren** [comment]
This issue should now be resolved. It took more than `cp.unref()` in order to detach the child process. I bumped the dependency as patch so reinstalling alfy does the trick.

**Pull request closed without merging**
