### PR TITLE
Add root level `variables` option

### LINKED ISSUE #43: Support setting Alfred variables with alfy.output
You can [set variables in Alfred](https://www.alfredforum.com/topic/9070-how-to-workflowenvironment-variables/) by writing to stdout using a special JSON format. It would be handy if `alfy.output` supported this, perhaps in a special `variables` key:

```javascript
alfy.output([
  { title: 'Google', arg: 'https://www.google.com', variables: { browser: 'Chrome' },
  { title: 'Mozilla', arg: 'https://www.mozilla.org', variables:  { browser: 'Firefox' } }
])
```

Or as a second argument:

```javascript
// backwards compatible, but less elegant
alfy.output([
  { title: 'Google', arg: 'https://www.google.com' },
  { title: 'Mozilla', arg: 'https://www.mozilla.org' }
], [
  { browser: 'Chrome' },
  { browser: 'Firefox' }
])
```

I'm happy to write a pull request if this seems worthwhile.

## JSON Format

The format for emitting variables isn't complicated, but life would be easier if Alfy handled it.

### Emit a string and set variables

```javascript
// The root `alfredworkflow` key is required.
// Without it, Alfred will pass the object to the next node in the workflow like normal.
{
  "alfredworkflow": {
    "arg": "https://www.google.com",
    "variables": {"browser": "Chrome"}
  }
}
```

### Emit multiple items and set variables

```javascript
// `arg` is a stringified `alfredworkflow` object
{
  "items": [{
    "title": "Google",
    "arg": "{\"alfredworkflow\": {\"arg\": \"https://www.google.com\", \"variables\": {\"browser\": \"Chrome\"}}}"
  }]
}
```

Note, you can access Alfred variables through the environment:

```javascript
const browser = process.env.browser
```

### PR DESCRIPTION
**Pull request by jopemachine**
## Related Issue

Fixes #43

## Usage

```js
alfy.output(
	[
		{
			title: 'API key register',
		}
	],
	{ 
		variables: {
            "apiKey": apiKey,
            "error": errorOccured
        } 
	}
);
```

## Test

Here is test code.

```js
const alfy = require("alfy");

const apiKey = "some API key";
const errorOccured = false;

alfy.output(
	[
		{
			title: 'API key register',
		}
	],
	{ 
		variables: {
            "apiKey": apiKey,
            "error": errorOccured
        } 
	}
);
```

And this is the debug log.

I logged  `{var:apiKey}, {allVars}`.

```
[16:07:39.158] alfred-evernote-workflow[Script Filter] Queuing argument ''
[16:07:39.878] alfred-evernote-workflow[Script Filter] Script with argv '(null)' finished
[16:07:39.880] alfred-evernote-workflow[Script Filter] {
	"items": [
		{
			"title": "API key register"
		}
	],
	"variables": {
		"apiKey": "some API key",
		"error": false
	}
}
[16:07:39.944] alfred-evernote-workflow[Script Filter] Processing complete
[16:07:39.945] alfred-evernote-workflow[Script Filter] Passing output '' to Debug
[16:07:39.946] alfred-evernote-workflow[Debug] some API key, {allVars}

```

You can check variables property works by the above test log.

Please let me know if there's anything lacking.

### CODE REVIEW

**Comment by jopemachine** [comment]
And about item-level variables,

I think we don't need additional work because we can handle it by the present's code.

If you don't think so, or there is something we need to do, pls let me know.

**Comment by jopemachine** [comment]
Do we still need more work about docs?

If so, could I get some hints about what should be included in the document?

**Comment by stdavis** [comment]
This would be super-helpful when attempting to post a message using Alfred's "Post Notification" output. Right now, the best I can get is a stringified object...
image

**Comment by sindresorhus** [comment]
@stdavis If you need this, help reviewing this PR is welcome :)

**Comment by sindresorhus** [comment]
> I think you need to put some more work into the docs.

This still applies.

**Comment by jopemachine** [comment]
I've added an example using root-level `variable` to README.md.

In fact, the screenshot I just uploaded doesn't look good to me. 
(Especially, compared to other neat screenshots)

But, I updated this because I want to know whether this example explains enough how to use variables.

I would appreciate it if you let me know if this example still doesn't explain enough how to use variable to users.

**Comment by jopemachine** [comment]
To be honest, I don't have an idea about how to reinforce the document.
I would be very grateful if anyone could do the work or give me some advice :)

**Comment by sindresorhus** [comment]
I appreciate the effort, but it's simply not close to being mergeable and I don't currently have the time to clean it up.

**Pull request closed without merging**
