### PR TITLE
use cache-conf module

### PR DESCRIPTION
**Pull request by SamVerschueren**
I needed that piece of code in another module so I extracted it in a separate package [cache-conf](https://github.com/SamVerschueren/cache-conf) which I should've done in the first place :).

### CODE REVIEW

**Comment by sindresorhus** [comment]
Hah, I have a todo note somewhere about asking you to do that.

**Comment by sindresorhus** [comment]
I think https://github.com/SamVerschueren/cache-conf/issues/1 needs to be fixed first, though, as it's documented here to work like `conf`.

**Comment by SamVerschueren** [comment]
:+1:

**Comment by SamVerschueren** [comment]
Resolved that `cache-conf` issue and bumped the version here.

**Pull request merged**
