### PR TITLE
add related packages

### PR DESCRIPTION
**Pull request by SamVerschueren**
Or do you want to show them more in the beginning of the readme?

### CODE REVIEW

**Comment by sindresorhus** [comment]
Both

**Comment by SamVerschueren** [comment]
Care to review/merge #16 first before I start fiddling with the readme :p?

**Comment by sindresorhus** [comment]
#16 is merged.

**Comment by SamVerschueren** [comment]
Also added [generator-alfred](https://github.com/SamVerschueren/generator-alfred).

I used small `tips` to inform the user about some extra tools they can use. Otherwise I couldn't find a good way of blending that content in.

**Comment by sindresorhus** [comment]
Cool. That's indeed a good way to do it.

**Pull request merged**
